version: "3.9"
services:
  db:
    platform: linux/amd64
    image: mysql:8.0.28
    container_name: barak_mysql
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MYSQL_DATABASE --password=$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55  
    ports:
      - 3306:3306  
    volumes:
      - db-data:/var/lib/mysql
  node:
    build: ./node
    container_name: barak_node
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=super-app
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  php:
    build: ./php
    container_name: barak_php
    ports:
      - 80:80
    volumes:
      - ./php/:/var/www/html/  
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true  

volumes:
  db-data:
  php: